/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
  order_all: () => import("@/views/order/all/index.vue"),
  order_kekebang: () => import("@/views/order/kekebang/index.vue"),
  order_mf178: () => import("@/views/order/mf178/index.vue"),
  order_xianzhuanxia: () => import("@/views/order/xianzhuanxia/index.vue"),
  platform: () => import("@/views/platform/index.vue"),
  platformapi_api: () => import("@/views/platformapi/api/index.vue"),
  "product_phone-location": () => import("@/views/product/phone-location/index.vue"),
  "product_set-menu": () => import("@/views/product/set-menu/index.vue"),
  product_type: () => import("@/views/product/type/index.vue"),
  "system_user-grade": () => import("@/views/system/user-grade/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  user: () => import("@/views/user/index.vue"),
};
