/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'order',
    path: '/order',
    component: 'layout.base',
    meta: {
      title: 'order',
      i18nKey: 'route.order',
      icon: 'mdi:shopping-cart',
      order: 2
    },
    children: [
      {
        name: 'order_all',
        path: '/order/all',
        component: 'view.order_all',
        meta: {
          title: 'order_all',
          icon: 'mdi:clipboard-text-multiple-outline',
          i18nKey: 'route.order_all'
        }
      },
      {
        name: 'order_kekebang',
        path: '/order/kekebang',
        component: 'view.order_kekebang',
        meta: {
          title: 'order_kekebang',
          icon: 'mdi:card-account-details-outline',
          i18nKey: 'route.order_kekebang'
        }
      },
      {
        name: 'order_mf178',
        path: '/order/mf178',
        component: 'view.order_mf178',
        meta: {
          title: 'order_mf178',
          icon: 'mdi:beehive-outline',
          i18nKey: 'route.order_mf178'
        }
      },
      {
        name: 'order_xianzhuanxia',
        path: '/order/xianzhuanxia',
        component: 'view.order_xianzhuanxia',
        meta: {
          title: 'order_xianzhuanxia',
          icon: 'mdi:briefcase-outline',
          i18nKey: 'route.order_xianzhuanxia'
        }
      }
    ]
  },
  {
    name: 'platform',
    path: '/platform',
    component: 'layout.base$view.platform',
    meta: {
      title: 'platform',
      i18nKey: 'route.platform',
      icon: 'mdi:cast-connected',
      order: 8,
      roles: ['SUPER_ADMIN']
    }
  },
  {
    name: 'platformapi',
    path: '/platformapi',
    component: 'layout.base',
    meta: {
      title: 'platformapi',
      i18nKey: 'route.platformapi',
      icon: 'mdi:api',
      order: 7,
      roles: ['SUPER_ADMIN']
    },
    children: [
      {
        name: 'platformapi_api',
        path: '/platformapi/api',
        component: 'view.platformapi_api',
        meta: {
          title: 'platformapi_api',
          i18nKey: 'route.platformapi_api',
          icon: 'mdi:apiarists'
        }
      }
    ]
  },
  {
    name: 'product',
    path: '/product',
    component: 'layout.base',
    meta: {
      title: 'product',
      i18nKey: 'route.product',
      icon: 'mdi:briefcase',
      order: 3
    },
    children: [
      {
        name: 'product_phone-location',
        path: '/product/phone-location',
        component: 'view.product_phone-location',
        meta: {
          title: 'product_phone-location',
          icon: 'mdi:cellphone-marker',
          i18nKey: 'route.product_phone-location',
          roles: ['SUPER_ADMIN']
        }
      },
      {
        name: 'product_set-menu',
        path: '/product/set-menu',
        component: 'view.product_set-menu',
        meta: {
          title: 'product_set-menu',
          icon: 'mdi:blur-linear',
          i18nKey: 'route.product_set-menu',
          auth: ['product:add'],
          roles: ['SUPER_ADMIN', 'AGENT']
        }
      },
      {
        name: 'product_type',
        path: '/product/type',
        component: 'view.product_type',
        meta: {
          title: 'product_type',
          i18nKey: 'route.product_type',
          icon: 'mdi:collage',
          order: 3,
          roles: ['SUPER_ADMIN']
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'carbon:cloud-service-management',
      order: 8,
      roles: ['SUPER_ADMIN']
    },
    children: [
      {
        name: 'system_settings',
        path: '/system/settings',
        component: 'view.system_settings',
        meta: {
          title: 'system_settings',
          icon: 'mdi:pause-octagon-outline',
          i18nKey: 'route.system_settings'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user',
          icon: 'ic:round-manage-accounts',
          order: 1
        }
      },
      {
        name: 'system_user-grade',
        path: '/system/user-grade',
        component: 'view.system_user-grade',
        meta: {
          title: 'system_user-grade',
          i18nKey: 'route.system_user-grade',
          hideInMenu: true
        }
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base$view.user',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      icon: 'mdi:user',
      hideInMenu: true
    }
  }
];
