# 优化后的配置文件示例
app:
  name: "recharge-go"
  version: "2.0.0"
  environment: "development"  # development, staging, production
  port: 8080
  host: "0.0.0.0"
  debug: true
  timeout: "30s"

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "qynfqepwq"
  name: "recharge-new"
  charset: "utf8mb4"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: "1h"
  ssl_mode: "disable"
  slow_threshold: "1s"
  log_level: "info"
  
  # 读写分离配置（可选）
  read_replicas:
    - host: "localhost"
      port: 3307
      user: "readonly"
      password: "readonly_password"
      name: "recharge_db"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"

logger:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, console
  output: "logs/app.log"  # stdout or file path
  max_size: 100  # MB
  max_backups: 5
  max_age: 30  # days
  compress: true
  caller: true
  stacktrace: true

security:
  jwt:
    secret: "your-super-secret-jwt-key-change-this-in-production"
    expiration: "24h"
    issuer: "recharge-go"
    skip_paths:
      - "/api/v1/user/login"
      - "/api/v1/user/register"
      - "/health"
      - "/metrics"

api:
  rate_limit:
    enabled: true
    rps: 100  # requests per second
    burst: 200
    window: "1m"
    skip_paths:
      - "/health"
      - "/metrics"
  
  cors:
    allow_origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
    allow_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allow_headers:
      - "Origin"
      - "Content-Type"
      - "Authorization"
      - "X-Request-ID"
    expose_headers:
      - "X-Request-ID"
    allow_credentials: true
    max_age: 86400  # 24 hours